sudo: required
language: node_js
node_js:
- '8'
notifications:
  email: false
services:
- docker
cache:
  yarn: true
  directories:
  - node_modules
branches:
  only:
  - master
  - develop
  - disaster-recover
  - v2.4.2
install: yarn
script: npm run build
before_deploy:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t qiansy/ebackup:dev-latest .
- docker tag qiansy/ebackup:dev-latest qiansy/ebackup:v2.4.2
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  - provider: script
    script: bash ./build/docker_push.sh develop
    on:
      branch:
        - develop
  - provider: script
    script: bash ./build/docker_push.sh master
    on:
      branch:
        - master
  - provider: script
    script: bash ./build/docker_push.sh disaster-recover
    on:
      branch:
        - disaster-recover
  - provider: script
    script: bash ./build/docker_push.sh v2.4.2
    on:
      branch:
        - v2.4.2
