sudo: required
language: node_js
node_js:
  - "8"
services:
  - docker
cache:
  yarn: true
  directories:
    - node_modules
install: yarn
script: npm run build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t chenzhq/ebackup:dev-latest .
deploy:
  provider: script
  script: bash ./build/docker_push.sh
  on:
    branch: develop