sudo: required
language: node_js
node_js:
  - "8"
notifications:
  email: false
services:
  - docker
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
  - master
  - develop
install: yarn
script: npm run build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t chenzhq/ebackup:dev-latest .
  - docker tag chenzhq/ebackup:dev-latest chenzhq/ebackup:latest
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  - provider: script
    script: bash ./build/docker_push.sh develop
    on:
      branch: 
        - develop
  - provider: script
    script: bash ./build/docker_push.sh master
    on:
      branch: 
        - master
  - provider: releases
    api_key:
      secure: 5f090d3b518284fefcddbdcd1dc1f0396ebcd04a
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      all_branches: true
